name = "myAnalytics"
uuid = "12345678-1234-1234-1234-123456789abc"
version = "0.1.0"
authors = ["Steve"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StateSpaceLearning = "971c4b7c-2c4e-4bac-8525-e842df3cde7b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgParse = "1.2.0"
Dates = "1.11.0"
JSON = "1.2.0"
Oxygen = "1.7.5"
Parameters = "0.12.3"
StateSpaceLearning = "2.0.15"
Statistics = "1.11.1"
julia = "1.6"
