name = "myAnalytics"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Steve"]
version = "0.1.0"

[deps]
Oxygen = "4f8fbe84-2c4e-40db-93d7-a95ba6e4f5a1"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Dates = "ade2ca70-3891-5945-98fb-52f0b215db09"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Parameters = "d96e819e-fc66-5662-9728-84c5a19d735c"

[compat]
Oxygen = "0.3"
JSON = "0.21"
julia = "1.6"
