name = "ssl"
uuid = "a940effc-f817-48bc-a72f-df0624c85d9a"
version = "0.1.0"
authors = ["Steve Kuhlman <3463852+spk57@users.noreply.github.com>"]

[deps]
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
StateSpaceLearning = "971c4b7c-2c4e-4bac-8525-e842df3cde7b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
OpenSSL_jll = "3.5.1"
StateSpaceLearning = "2.0.12"
Statistics = "1.11.1"
